from pathlib import Path
ROOT=Path(__file__).resolve().parent
old=(ROOT/'site-template.html').read_text()
style=old[old.index('<style>')+7:old.index('</style>')].split('html{scroll-behavior:smooth;')[0]
comparison=old[old.index('<section class="comparison"'):old.index('<script id="case-data"')]
comparison=comparison.replace('城市的覆寫 · 三地平面研究 · 歷史判讀線稿 v1','城市的覆寫 · 三地平面研究 · 描圖與航照分組 v2')
comparison=comparison.replace('每案 Before／現況採相同地理範圍、北向與畫面比例；三案之間範圍不同，請依比例尺比較，不能直接用畫面長度比較尺度。兩圖放大以中心為基準，比例尺同步更新。官方方案原圖另列，不與現況混成「已實現」的圖面。','每案描圖使用共同重點視窗，完整範圍在航照組另外列出；三案之間範圍不同，應以比例尺比較。歷史是可見屋頂與路面判讀，現況建物是官方測繪足跡，兩者不可直接相減估計拆建面積。圖上同號標記為位置索引，不是精確變更界線。官方未來方案另列。')
comparison=comparison.replace('歷史線稿為人工航照判讀初稿，依原始影像的可見道路與屋頂選點描繪，沒有借用今天的建物輪廓冒充歷史。尚未逐棟完成、未做地面控制點校正或精度驗證；實線表示可見部分，虛線表示樹冠遮蔽的低可信度河岸。它適合討論地景結構，不適用於工程定位、面積計算或建物消失數量統計。','歷史線稿 v2 在重點視窗補畫可辨識屋頂、路面與地表，斜線遮罩明示陰影與尚待判讀區。尚未完成全區逐棟歷史測繪；未經地面控制點校正，也未驗證精度。Cross-Bronx 河流線已重新依放大航照修正，樹冠下水界仍屬概略判讀。空白底色為未分類地表，不代表當時無建物。')
comparison=comparison.replace('日本歷史：國土地理院 gazo1 航照，1974–1978。','日本航照：國土地理院 gazo1（1974–1978）及 nendophoto2019（2019 年度）；後者不是 2026 現況。')
css='''#officialMap.annotated{position:relative;margin:18px auto}#officialMap.annotated>img{width:100%;max-height:none;margin:0;display:block}#officialOverlay{position:absolute;inset:0;pointer-events:none}#officialOverlay svg{width:100%;height:100%;display:block}html{scroll-behavior:smooth;scroll-padding-top:20px}.worknav{display:flex;gap:24px;flex-wrap:wrap;border-bottom:2px solid var(--ink);padding:10px 0 18px}.worknav a{font-size:15px;font-weight:650}.sectionhead{display:flex;justify-content:space-between;gap:20px;align-items:end;margin:30px 0 15px}.sectionhead>span{font-size:13px;color:var(--muted)}.drawing,.markersLayer{position:absolute;inset:0}.drawing svg,.markersLayer svg{width:100%;height:100%;display:block}.markersLayer{pointer-events:none}.planframe .mapcontent{background:#f7f7f2}.chip{display:inline-block;width:20px;height:13px;border:1px solid #9ba5a2;margin-right:7px;vertical-align:middle}.building{background:#e1dbcc}.water{background:#cee6ed}.land{background:#e3eadf}.pending{background:repeating-linear-gradient(-45deg,#f4f0e7 0 4px,#c8b99c 4px 5px)}.changes{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin:15px 0 35px}.changeitem{border-top:3px solid var(--change);padding:14px 0}.changeitem button{display:flex;text-align:left;gap:13px;width:100%;border:0;padding:8px;background:transparent}.changeitem button[aria-pressed=true]{background:#e2e8e5;color:var(--ink)}.changeitem button>b{border:2px solid var(--change);border-radius:50%;min-width:32px;height:32px;text-align:center;color:var(--change)}.changeitem button span{font-size:12px;color:var(--change)}.changeitem strong{display:block;font-size:17px;color:var(--ink)}.changeitem p{font-size:14px;margin:12px 0}.changeitem em{font-style:normal;font-size:12px;background:#e5e9e5;margin-right:7px;padding:3px 5px}.changeitem small{font-size:12px;color:var(--muted);display:block}.photoframe>img{position:absolute;max-width:none;object-fit:fill}.focusbox{position:absolute;border:3px solid #db603f;box-shadow:0 0 0 1px white;pointer-events:none}.photoframe{background:#ddd}#aerials{border-top:2px solid var(--ink);padding-top:5px}.controls>span{font-size:12px;color:var(--muted)}@media(max-width:760px){.changes{grid-template-columns:1fr}.sectionhead{display:block}.worknav{gap:12px}.maptitle{min-height:64px}.planframe{max-height:none}}'''
page='<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><title>城市的覆寫｜描圖與航照分組對照</title><style>'+style+css+'</style></head>'+(ROOT/'site-v2-body.html').read_text()+comparison+'<script id="case-data" type="application/json">__CASE_DATA__</script><script>'+(ROOT/'site-v2.js').read_text()+'</script></body></html>'
(ROOT/'site-template.html').write_text(page)
