const cases=JSON.parse(document.getElementById('case-data').textContent);let selected=0,activeChange=null;const $=id=>document.getElementById(id);const put=(id,text)=>$(id).textContent=text;
const colors={removed:'#b74632',added:'#237752',changed:'#aa7822',retained:'#126b95',planned:'#785795',pending:'#7b776d'};
const labels={removed:'拆除',added:'新增',changed:'配置／用途改變',retained:'保留關係',planned:'未來方案',pending:'待核對'};
document.querySelector('.tabs').innerHTML=cases.map((c,i)=>`<button type="button" data-case="${i}" aria-pressed="${i===0}">${c.name}<small>${c.city}</small></button>`).join('');
$('three').innerHTML=cases.map((c,i)=>`<article class="mini"><div class="eyebrow">0${i+1} / ${c.city}</div><h3>${c.verb} · ${c.name}</h3><img src="${c.current}" alt="${c.name}完整範圍現況平面" loading="lazy"><p>${c.concept}</p><button type="button" data-case="${i}">回到此案對照 ↑</button></article>`).join('');
function markers(c){let b=c.focus.bbox;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b[0]} ${b[1]} ${b[2]-b[0]} ${b[3]-b[1]}">`+c.focus.changes.map(p=>`<g data-marker="${p.n}" opacity="${activeChange===null||activeChange===p.n?1:.25}"><circle cx="${p.xy[0]}" cy="${p.xy[1]}" r="${activeChange===p.n?10:8}" fill="white" stroke="${colors[p.kind]}" stroke-width="2"/><text x="${p.xy[0]}" y="${p.xy[1]+3.2}" text-anchor="middle" font-family="sans-serif" font-size="10" font-weight="700" fill="${colors[p.kind]}">${p.n}</text></g>`).join('')+'</svg>'}
function updatePlans(){const c=cases[selected],z=Number($('zoom').value);put('zoomvalue',z+'×');document.querySelectorAll('.planframe').forEach(f=>{f.style.setProperty('--zoom',z);f.querySelector('.scale').style.width=`calc(${100/c.focusWidth*100*z}% + 16px)`});['beforeMarkers','afterMarkers'].forEach(id=>{$(id).innerHTML=markers(c);$(id).hidden=!$('markers').checked});document.querySelectorAll('[data-change]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.change)===activeChange))}
function updatePhotos(){const c=cases[selected],crop=$('aerialFocus').checked,b=c.focus.bbox,[w,h]=c.originalView;document.querySelectorAll('.photoframe').forEach(f=>{f.style.setProperty('--ratio',crop?c.focusRatio:c.ratio);const im=f.querySelector('img');im.style.width=crop?w/(b[2]-b[0])*100+'%':'100%';im.style.height=crop?h/(b[3]-b[1])*100+'%':'100%';im.style.left=crop?-b[0]/(b[2]-b[0])*100+'%':'0';im.style.top=crop?-b[1]/(b[3]-b[1])*100+'%':'0';const box=f.querySelector('.focusbox');box.hidden=crop;box.style.left=b[0]/w*100+'%';box.style.top=b[1]/h*100+'%';box.style.width=(b[2]-b[0])/w*100+'%';box.style.height=(b[3]-b[1])/h*100+'%'})}
function show(i){selected=i;activeChange=null;const c=cases[i];$('zoom').value=1;document.querySelectorAll('.tabs button').forEach((b,j)=>b.setAttribute('aria-pressed',j===i));put('location',c.en);put('casetitle',c.name+'｜'+c.verb);put('status',c.status);put('scope',c.focus.name+' · '+c.focusWidth+' × '+c.focusHeight+' m');put('beforeyear',c.year);put('afteryear',c.after);$('beforeDrawing').innerHTML=c.focusBefore;$('afterDrawing').innerHTML=c.focusAfter;document.querySelectorAll('.planframe').forEach(f=>f.style.setProperty('--ratio',c.focusRatio));put('aftercaption','官方建物足跡、道路及水域圖層；各圖層測製年不同。現況不包含尚未落成的未來方案。');for(const side of ['before','after']){$(side+'Download').href='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(c[side==='before'?'focusBefore':'focusAfter']);$(side+'Download').download=c.id+'_focus_'+side+'.svg'}
$('changes').innerHTML=c.focus.changes.map(p=>`<article class="changeitem" style="--change:${colors[p.kind]}"><button type="button" data-change="${p.n}" aria-pressed="false"><b>${p.n}</b><span>${labels[p.kind]}<strong>${p.title}</strong></span></button><p><em>歷史</em>${p.before}</p><p><em>現況</em>${p.after}</p><small>${p.note}</small></article>`).join('');put('oldPhotoYear',c.year);put('newPhotoYear',c.recentYear);$('oldPhoto').src=c.aerial;$('oldPhoto').alt=c.name+' '+c.year+' 航照';$('newPhoto').src=c.recent;$('newPhoto').alt=c.name+' '+c.recentYear+' 航照';put('photoNote',c.id==='nihonbashi'?'日本橋採 GSI 1974–78 與 2019 年度航照。2019 影像只作年代對照，並不是 2026 現況；現況描圖與官方工程方案請分別閱讀。':'NYC 官方 '+c.year+' 與 2024 航照。同範圍對照；影像拼接、陰影與屋頂透視仍可能產生偏移。');['concept','fact','post','question'].forEach(k=>put(k,c[k]));put('read','圖上 1–3 號與改變項目一一對應。先辨認可確認的物理改變，再區分保留、待核對與未來方案；斜線區保留判讀不確定性。');$('source').href=c.source;$('timeline').innerHTML=c.timeline.map(([t,s])=>`<div class="event"><b>${t}</b>${s}</div>`).join('');put('officialtitle',c.official_img?'官方方案平面｜與現況分開閱讀':'已落成地景｜2024 航照參照');$('officialimg').src=c.official_img||c.recent;$('officialimg').alt=c.name+(c.official_img?'官方方案平面節錄':'2024 水岸航照');put('officialnote',c.official_note);$('officialOverlay').innerHTML=c.officialOverlay||'';$('officialOverlay').hidden=!c.officialOverlay;$('officialMap').classList.toggle('annotated',!!c.officialOverlay);updatePlans();updatePhotos()}
document.addEventListener('click',e=>{const c=e.target.closest('[data-case]');if(c){show(Number(c.dataset.case));if(c.closest('#three'))$('workspace').scrollIntoView({behavior:'smooth'})}const b=e.target.closest('[data-change]');if(b){activeChange=activeChange===Number(b.dataset.change)?null:Number(b.dataset.change);$('markers').checked=true;updatePlans()}});$('markers').addEventListener('change',updatePlans);$('zoom').addEventListener('input',updatePlans);$('reset').addEventListener('click',()=>{$('zoom').value=1;$('markers').checked=true;activeChange=null;updatePlans()});$('aerialFocus').addEventListener('change',updatePhotos);show(0);
